# Generated by Django 4.2.8 on 2023-12-15 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_clientesproductos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClientesProductos',
            new_name='Clientes',
        ),
    ]
