# Generated by Django 4.2.8 on 2023-12-16 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_productos_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='precio',
            field=models.IntegerField(default=0),
        ),
    ]
